import * as fs from "node:fs";
import * as path from "node:path";

const manifest = fs.readFileSync("package.json", "utf8");
const match = /"version"\s*:\s*"([^"]+)"/.exec(manifest);
if (match?.[1] === undefined) throw new Error("package.json has no version");

const output = path.join("src", "cli", "version.ts");
const source = `/** Generated by \`npm run codegen\`; do not edit by hand. */\nexport const version = ${JSON.stringify(match[1])};\n`;

if (fs.readFileSync(output, "utf8") !== source) fs.writeFileSync(output, source);
